# -*- coding: utf-8 -*-
{
    'name': 'SD Credit & Commission',
    'version': '19.0.1.1.0',
    'category': 'Sales',
    'summary': 'Credit exposure checks, managerial approval, and progressive commissions on sales orders',
    'depends': ['sale_management', 'account', 'sales_team'],
    'license': 'LGPL-3',
    'author': 'Ahmed',
    'data': [
        'data/sequence.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/commission_brackets.xml',
        'data/cron.xml',
        'reports/report_templates.xml',
        'reports/report.xml',
        'views/credit_log_views.xml',
        'views/commission_views.xml',
        'views/commission_bracket_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/dashboard_views.xml',
        'views/menus.xml',
    ],
    'assets': {},
    'installable': True,
    'application': False,
}
